server:
  port: 8080
  servlet:
    context-path: /
spring:
  main:
    web-application-type: ${mode}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
logging:
  level:
    root: info
    com.dqv5: debug
mode: servlet
